#General Params
verbose: TRUE
threads: 12
java_mem: 16G
overwrite_results: FALSE
clean_tmp_files: FALSE
plot_format: "pdf"

#in/out paths
input_path: "./input/"
results_path: "./results/"
#anaconda_bin_path: "/opt/anaconda/bin/"

### Reference Data Definition
reference_sequence_file: "hg38_phage.fa"
intervals_file: "SeqCap_EPI_CpGiant_hg38_custom_liftOver.bed"

# Specific Tools params
trimmomatic_MINLEN: 50
sqtk_omit: TRUE
sqtk_subset: 10000000
